import ModalProvider from '@/providers/ModalProvider'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import NavBar from '@/components/NavBar'
import Player from '@/components/Player'
import HydrationZustand from '@/components/HydrationZustand'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Coog Music',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <HydrationZustand>
          <ModalProvider />
          <NavBar>
            {children}
          </NavBar>
          <Player />

        </HydrationZustand>

      </body>
    </html>
  )
}
